### ISSUE TITLE
Problem with Kneed package.

### ISSUE THREAD

**Issue by bejnpenik** [alperaksac/cutESC#1]
Hi!

In newer version of the Kneed package, the function call :+1: 

> KneeLocator(x_axis, hist, S=1.0, invert=False, direction='decreasing')

fails, because the option _invert_ is deprecated. There is option an option _curve_. Is the _curve='convex'_ now correct?

Regards,

Branislav

**Comment by alperaksac** [comment]
Thank you, KneeLocator and other functions are updated.
